# Use root/example as user/password credentials
version: '3.3'
volumes:
    data:
services:
    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=organize_pdf_dev
            - MYSQL_ROOT_PASSWORD=senha

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin:latest
    #     links:
    #         - db
    #     ports:
    #         - 80:80
    #     environment:
    #         - PMA_ARBITRARY=1

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
